### ISSUE TITLE
FlxG.addBitmap has unsafe fallback to default png

### ISSUE THREAD

**Issue by jquave** [FlixelCommunity/flixel#150]
Not sure what side effects could occur from this, but the fallback to FlxSprite.ImgDefault gives an error when compiling:

> /src/org/flixel/FlxG.as(754): col: 38 Error: Access of possibly undefined property  ImgDefault through a reference with static type Class.
> 
> return FlxG.addBitmap(FlxSprite.ImgDefault, Reverse);

Additionally, the FlxSprite.ImgDefault has no guarantee the game will have a data/default.png file. What happens if this is missing?

**Comment by IQAndreas** [comment]
> What happens if this is missing?

That image is embedded when Flixel is compiled. This means:
- **If they use the pre-made SWC** - they don't need to include the image, it will already be embedded and ready inside of the SWC.
- **If they copy the Flixel source into their project folder** - the image should tag along with all of the classes. If they manually remove the image, they will receive an error, just the same as if they remove any class from the Flixel source. This shouldn't ever be an "accidental" issue.

But that bug is my fault, and will be fixed this weekend. Thanks for catching it. :)

**Comment by jquave** [comment]
Got it, I'm still learning Flixel. I'm doing everything in mxmlc to make sure I know how it all works. I see now flixel has the data directory with that image in it. So we are basically guaranteed to have the image exist.

[My commit](https://github.com/jquave/flixel/commit/f431198019812c23a305e7e83c0b45fc4179ea07) fixes the compile problem, but not sure how it effects the intended usage of ImgDefault.

**Comment by IQAndreas** [comment]
Resolved by 949b914f80ebda55eeaa9377c422a000a912327b
